#!/bin/bash
until nc -z localhost 7070
do
    echo "Waiting for the StackState interface to become healthy..."
    sleep 5
done
su -c "/opt/stackstate/simulator/demo/steps/step_1.sh" -s /bin/bash stackstate
su -c "/opt/stackstate/simulator/demo/steps/step_2.sh &" -s /bin/bash stackstate
